# Generated by Django 5.2.9 on 2026-01-02 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservation', '0001_initial'),
        ('restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='reservation.reservation'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_source', to='reservation.reservation'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='restaurant.table'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['date', 'status'], name='reservation_date_ef5aeb_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['date', 'start_time', 'end_time'], name='reservation_date_269d57_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['table', 'date', 'start_time'], name='reservation_table_i_86e7b2_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['reservation', 'status'], name='reservation_reserva_152016_idx'),
        ),
        migrations.AddIndex(
            model_name='waitlistentry',
            index=models.Index(fields=['table', 'date', 'start_time', 'status'], name='reservation_table_i_178021_idx'),
        ),
        migrations.AddIndex(
            model_name='waitlistentry',
            index=models.Index(fields=['user', 'status'], name='reservation_user_id_1bedc6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='waitlistentry',
            unique_together={('user', 'table', 'date', 'start_time', 'end_time')},
        ),
    ]
