# Generated by Django 5.2.9 on 2026-01-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitlistentry',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.RemoveField(
            model_name='waitlistentry',
            name='payment_deadline',
        ),
        migrations.RemoveField(
            model_name='waitlistentry',
            name='position',
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('stale', 'Stale')], default='pending', max_length=15),
        ),
    ]
